// Generates a Remix Icon subset (woff2 + css) containing only the glyphs the
// UI actually uses. Scans src/ for `ri-*` class names, so adding an icon to a
// component and re-running `npm run icons` is all that's needed.
// `--check` exits non-zero if the committed subset is stale (used by tests).
import { readFileSync, writeFileSync, readdirSync, statSync, mkdirSync, existsSync } from 'node:fs';
import { join, dirname, extname } from 'node:path';
import { fileURLToPath } from 'node:url';
import subsetFont from 'subset-font';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const srcDir = join(root, 'src');
const outDir = join(srcDir, 'icons');
const fontDir = join(root, 'node_modules', 'remixicon', 'fonts');
const check = process.argv.includes('--check');

function walk(dir, acc = []) {
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    if (p === outDir) continue;
    if (statSync(p).isDirectory()) walk(p, acc);
    else if (['.ts', '.tsx'].includes(extname(p))) acc.push(p);
  }
  return acc;
}

const used = new Set();
for (const file of walk(srcDir)) {
  for (const m of readFileSync(file, 'utf8').matchAll(/\bri-([a-z0-9]+(?:-[a-z0-9]+)*-(?:line|fill))\b/g)) {
    used.add(m[1]);
  }
}
const names = [...used].sort();

const sourceCss = readFileSync(join(fontDir, 'remixicon.css'), 'utf8');
const glyphs = names.map((name) => {
  const m = sourceCss.match(new RegExp(`\\.ri-${name}:before\\s*\\{\\s*content:\\s*"\\\\([0-9a-f]+)"`));
  if (!m) throw new Error(`Unknown Remix Icon: ri-${name}`);
  return { name, code: m[1] };
});

const css = [
  '/* GENERATED by scripts/build-icons.mjs — do not edit. Run `npm run icons`. */',
  '/* Remix Icon v4 subset — Remix Icon License 1.0 (https://remixicon.com) */',
  '@font-face {',
  "  font-family: 'remixicon';",
  "  src: url('./remixicon-subset.woff2') format('woff2');",
  '  font-display: block;',
  '}',
  "[class^='ri-'],",
  "[class*=' ri-'] {",
  "  font-family: 'remixicon' !important;",
  '  font-style: normal;',
  '  font-weight: normal;',
  '  -webkit-font-smoothing: antialiased;',
  '}',
  ...glyphs.map((g) => `.ri-${g.name}:before { content: '\\${g.code}'; }`),
  '',
].join('\n');

const cssPath = join(outDir, 'icons.css');
if (check) {
  const current = existsSync(cssPath) ? readFileSync(cssPath, 'utf8') : '';
  if (current !== css) {
    console.error('Icon subset is stale. Run `npm run icons`.');
    process.exit(1);
  }
  console.log(`icons ok (${names.length} glyphs)`);
  process.exit(0);
}

const text = glyphs.map((g) => String.fromCodePoint(parseInt(g.code, 16))).join('');
const woff2 = await subsetFont(readFileSync(join(fontDir, 'remixicon.ttf')), text, { targetFormat: 'woff2' });
mkdirSync(outDir, { recursive: true });
writeFileSync(join(outDir, 'remixicon-subset.woff2'), woff2);
writeFileSync(cssPath, css);
console.log(`icons: ${names.length} glyphs, ${woff2.length} bytes woff2`);
